### ISSUE TITLE
Question for Forward lld (gaussian prior) and entropy estimation in MMILB Module.

### ISSUE THREAD

**Issue by Columbine21** [declare-lab/Multimodal-Infomax#1]
https://github.com/declare-lab/Multimodal-Infomax/blob/34f92d25fe3a9931356eb775798f8a3f2854e78b/src/modules/encoders.py#L152

Is "positive" vector (above in line 152) for the p(y|x) ~ N(y|µθ1(x), σ2 (x) I)? where is the -(lnσ + C) items in the probability density function for Normal distribution ?

**Comment by Columbine21** [comment]
Many thx, and looking forwards to your reply.

**Comment by Clement25** [comment]
Hi, @Columbine21. For the part of BA bound maximization we refer to the implementation of vCLUB, a similar two-stage training approach but for mutual information minimization instead of maximization, https://github.com/Linear95/CLUB/blob/master/MI_DA/MNISTModel_DANN.py (sorry for pasting the wrong link and we have modified that).

**Comment by Columbine21** [comment]
Thx a lot.

**Comment by yangmiemiemie1** [comment]
So where is the -(lnσ + C) items in the probability density function for Normal distribution ?Why is it missing?
