### ISSUE TITLE
Using test loss to choose the best model?

### ISSUE THREAD

**Issue by yufengyin** [declare-lab/Multimodal-Infomax#4]
Hi,

In solver.py line 295-316, it seems like you are using the test loss (MAE) to choose the best model.

I think it's not correct. Instead, we can only use the validation results to choose the best model.

**Comment by Clement25** [comment]
Thanks for your discovery. Actually here we don't. 

Note in
 https://github.com/declare-lab/Multimodal-Infomax/blob/9a6dc8f2bfa861cd447ba65c6a037cd7dd24f473/src/solver.py#L295
 the outer loop is still conditioned on the valid loss.

We write in this style to save time, because if at some epoch valid loss reaches a new lowest but test loss doesn't, we can early stop the training process between the current step and last best step.

**Comment by Clement25** [comment]
In this case, we can set the maximum training epoch to 1 as what I replied above.

**Comment by yufengyin** [comment]
I see... Thanks

> In this case, you can set the maximum training epoch to 1 as I replied above.
